services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nextjsapp:/workspace/nextjsapp
    working_dir: /workspace/nextjsapp #コンテナ内の作業ディレクトリ
    ports:
      - "3000:3000"
      - "5555:5555" #追加
    environment:
      - DATABASE_URL=${DATABASE_URL} #追加
    depends_on:
      - db #追加

  db: #追加
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes: #追加
  postgres_data:
