version: "3.9"

services:
  nextjs:
    build:
      context: ../nextjsapp
      dockerfile: ../docker/Dockerfile.prod
    container_name: nextjs_prod
    ports:
      - "3000:3000"
    env_file:
      - ../env/.env.production
    environment:
      NODE_ENV: "production"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
